vich_uploader:
  db_driver: orm

  mappings:
    cotech_vacarm:
      uri_prefix: /images/cotech_vacarm
      upload_destination: "%kernel.project_dir%/public/images/cotech_vacarm"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    scripts:
      uri_prefix: /uploads/scripts
      upload_destination: "%kernel.project_dir%/public/uploads/scripts"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true
      namer_keep_extension: true
