# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  locale: "fr"
  scripts_directory: "%kernel.project_dir%/public/uploads/scripts"
  meteo_france_token: "%env(METEO_FRANCE_TOKEN)%"
  meteo_france_user: "%env(METEO_FRANCE_USER)%"
  meteo_france_base_url: "%env(METEO_FRANCE_BASE_URL)%"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Services\ApimeteocentreService:
    arguments:
      # $apiKey_cnrs: "%env(WEATHERLINK_API_KEY_CNRS)%"
      # $apiSecret_cnrs: "%env(WEATHERLINK_API_SECRET_CNRS)%"

      # $apiKey_droue: "%env(WEATHERLINK_API_KEY_DROUE)%"
      # $apiSecret_droue: "%env(WEATHERLINK_API_SECRET_DROUE)%"

      # $apiKey_bazoches: "%env(WEATHERLINK_API_KEY_BAZOCHES)%"
      # $apiSecret_bazoches: "%env(WEATHERLINK_API_SECRET_BAZOCHES)%"

      $apiKey_ligair: "%env(LIGAIR_API_KEY)%"
      $apiSecret_ligair: "%env(LIGAIR_API_SECRET)%"

  App\Controller\Admin\BaseScriptCrudController:
    arguments:
      $scriptsDirectory: "%scripts_directory%"

  App\Services\MeteoFranceService:
    arguments:
      $meteoFranceToken: "%meteo_france_token%"
      $meteoFranceUser: "%meteo_france_user%"
      $meteoFranceBaseUrl: "%meteo_france_base_url%"
      $connection: "@doctrine.dbal.pgsql_connection"
